/-
Copyright (c) 2026 Jiabai Wang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiabai Wang
-/
import Mathlib.Data.Finset.Image
import Mathlib.RingTheory.Finiteness.Defs
import MyProject.Determinantalideals.Basic
import MyProject.Determinantalideals.Finite

/-!
# Determinantal ideals

This file defines the determinantal ideal generated by all `t × t` minors of the generic
`m × n` matrix, and proves basic lemmas about membership, monotonicity, finite generation,
and the degenerate case where no such minors exist.
-/

namespace Determinantal

section Ideal

variable (m n t : ℕ)
variable (k : Type*) [CommRing k]


/-- The ideal generated by all `t × t` minors of the generic `m × n` matrix. -/
def detIdeal : Ideal (MvPolynomial (Fin m × Fin n) k) :=
  Ideal.span (minorSet t)

/-- Every `t × t` minor belongs to the `t`-th determinantal ideal. -/
lemma minor_mem_detIdeal {m n t : ℕ} (I : MinorIndex m n t) :
    genericMinor I ∈ detIdeal m n t k := by
  exact Ideal.subset_span (minor_mem_minorSet (k := k) I)

/-- Monotonicity of determinantal ideals with respect to inclusion of the corresponding sets
of minors. -/
lemma detIdeal_mono {m n : ℕ} {t₁ t₂ : ℕ}
    (h : minorSet t₁ ⊆ minorSet (m := m) (n := n) (k := k) t₂) :
    detIdeal m n t₁ k ≤ detIdeal m n t₂ k := by
  exact Ideal.span_mono h

/-- The determinantal ideal generated by the `t × t` minors is contained in `J` iff every
`t × t` minor belongs to `J`. -/
lemma detIdeal_le_iff {m n t : ℕ} {J : Ideal (MvPolynomial (Fin m × Fin n) k)} :
    detIdeal m n t k ≤ J
      ↔ (minorSet (m := m) (n := n) (k := k) t ⊆ J) := by
  simpa [detIdeal] using
    (Ideal.span_le :
      Ideal.span (minorSet t) ≤ J
        ↔ minorSet (m := m) (n := n) (k := k) t ⊆ J)

/-- The determinantal ideal is the span of the range of the `minor` map. -/
lemma detIdeal_eq_span_range {m n : ℕ} (t : ℕ) :
    detIdeal m n t k=
      Ideal.span (Set.range (genericMinor (t := t))) := by
  rfl

/-- A finite set containing all `t × t` minors of the generic `m × n` matrix. -/
noncomputable def minorFinset (m n t : ℕ) : Finset (MvPolynomial (Fin m × Fin n) k) := by
  classical
  exact Finset.univ.image (genericMinor (t := t))

/-- The coercion of `minorFinset` to a set is exactly the range of `minor`. -/
lemma coe_minorFinset_eq_range (m n t : ℕ) :
    ((minorFinset k m n t : Finset (MvPolynomial (Fin m × Fin n) k)) :
        Set (MvPolynomial (Fin m × Fin n) k)) =
      Set.range (genericMinor (t := t)) := by
  classical
  ext f
  constructor
  · intro hf
    rcases Finset.mem_image.1 hf with ⟨I, -, rfl⟩
    exact ⟨I, rfl⟩
  · rintro ⟨I, rfl⟩
    exact Finset.mem_image.2 ⟨I, by simp, rfl⟩

/-- The determinantal ideal is the span of the finite set `minorFinset`. -/
lemma detIdeal_eq_span_minorFinset (m n t : ℕ) :
    detIdeal m n t k=
      Ideal.span (minorFinset k m n t : Set (MvPolynomial (Fin m × Fin n) k)) := by
  rw [detIdeal_eq_span_range k t, coe_minorFinset_eq_range k m n t]

/-- The determinantal ideal is finitely generated. -/
lemma detIdeal_FG (m n t : ℕ) :
    (detIdeal m n t k).FG := by
  classical
  refine ⟨minorFinset k m n t, ?_⟩
  exact (detIdeal_eq_span_minorFinset k m n t).symm

/-- If there are no `t × t` minors, then the set of such minors is empty. -/
lemma minorSet_eq_empty_of_isEmpty {m n t : ℕ} (h : IsEmpty (MinorIndex m n t)) :
    minorSet (m := m) (n := n) (k := k) t = ∅ := by
  ext f
  simp [minorSet]

/-- If there are no `t × t` minors, then the corresponding determinantal ideal is `⊥`. -/
lemma detIdeal_eq_bot_of_isEmpty {m n t : ℕ} (h : IsEmpty (MinorIndex m n t)) :
    detIdeal m n t k = ⊥ := by
  rw [detIdeal, minorSet_eq_empty_of_isEmpty k h]
  simp

end Ideal

end Determinantal
