import Mathlib

open scoped BigOperators

namespace Determinantal

/-! ### 0. Base setup -/

variable {k : Type*} [CommRing k]

abbrev R (m n : ℕ) (k : Type*) [CommRing k] := MvPolynomial (Fin m × Fin n) k

/-- The generic m×n matrix with entries X_{ij} as variables in `MvPolynomial`. -/
noncomputable def genericMatrix (m n : ℕ) (k : Type*) [CommRing k] :
    Matrix (Fin m) (Fin n) (R m n k) :=
  fun i j => MvPolynomial.X (i, j)

@[simp] lemma genericMatrix_apply {m n : ℕ} (i : Fin m) (j : Fin n) :
    genericMatrix (m := m) (n := n) k i j = (MvPolynomial.X (i, j) : R m n k) := rfl

/-! ### 1. Indices for minors -/

/--
Index data for a t×t minor:
choose t distinct rows and t distinct columns via embeddings.
-/
structure MinorIndex (m n t : ℕ) where
  row : Fin t ↪o Fin m
  col : Fin t ↪o Fin n

attribute [simp] MinorIndex.row MinorIndex.col

/-- The t×t minor of the generic matrix corresponding to `I`. -/
noncomputable def minor {m n : ℕ} {t : ℕ} (I : MinorIndex m n t) : R m n k :=
  Matrix.det <|
    Matrix.submatrix (genericMatrix (m := m) (n := n) k) I.row I.col

/-- The set of all t×t minors (as polynomials). -/
def minorSet {m n : ℕ} (t : ℕ) : Set (R m n k) :=
  { f | ∃ I : MinorIndex m n t, f = minor (m := m) (n := n) (k := k) I }

@[simp] lemma mem_minorSet_iff {m n : ℕ} {t : ℕ} {f : R m n k} :
    f ∈ minorSet (m := m) (n := n) (k := k) t
      ↔ ∃ I : MinorIndex m n t, f = minor (m := m) (n := n) (k := k) I := Iff.rfl

lemma minor_mem_minorSet {m n : ℕ} {t : ℕ} (I : MinorIndex m n t) :
    minor (m := m) (n := n) (k := k) I ∈ minorSet (m := m) (n := n) (k := k) t :=
  ⟨I, rfl⟩

/-! ### 2. Determinantal ideals -/

/-- The determinantal ideal generated by all t×t minors. -/
def detIdeal {m n : ℕ} (t : ℕ) : Ideal (R m n k) :=
  Ideal.span (minorSet (m := m) (n := n) (k := k) t)

lemma minor_mem_detIdeal {m n : ℕ} {t : ℕ} (I : MinorIndex m n t) :
    minor (m := m) (n := n) (k := k) I ∈ detIdeal (m := m) (n := n) (k := k) t := by
  -- immediate from `Ideal.subset_span`
  exact Ideal.subset_span (minor_mem_minorSet (m := m) (n := n) (k := k) I)

lemma detIdeal_mono {m n : ℕ} {t₁ t₂ : ℕ}
  (h : minorSet (m := m) (n := n) (k := k) t₁ ⊆ minorSet t₂) :
    detIdeal (m := m) (n := n) (k := k) t₁ ≤ detIdeal t₂ := by
  -- span is monotone
  exact Ideal.span_mono h

/-- The rank-≤r determinantal ideal is generated by (r+1)-minors. -/
abbrev rankIdeal {m n : ℕ} (r : ℕ) : Ideal (R m n k) := detIdeal (m := m) (n := n) (k := k) (r+1)

/-! ### 3. Anti-diagonal monomials (expected leading terms) -/

/--
Exponent vector of the "anti-diagonal" monomial of a t×t minor.

Typical expectation under an anti-diagonal (or suitable diagonal) term order:
  LM(minor I) = monomial (antiDiagExp I) 1
-/
noncomputable def antiDiagExp {m n : ℕ} {t : ℕ} (I : MinorIndex m n t) : (Fin m × Fin n) →₀ ℕ :=
  ∑ i : Fin t, Finsupp.single (I.row i, I.col (Fin.rev i)) 1

/-- The corresponding anti-diagonal monomial as a polynomial. -/
noncomputable def antiDiagMonom {m n : ℕ} {t : ℕ} (I : MinorIndex m n t) : R m n k :=
  MvPolynomial.monomial (antiDiagExp (m := m) (n := n) (t := t) I) (1 : k)

lemma antiDiagMonom_ne_zero {m n : ℕ} {t : ℕ} (I : MinorIndex m n t) :
    antiDiagMonom (m := m) (n := n) (k := k) I ≠ 0 := by
  -- This is usually true because coefficient is 1; keep as a small lemma placeholder.
  -- You may prove it using `MvPolynomial.monomial_eq_zero` (depending on the exact lemma names).
  sorry

/-! ### 4. Gröbner interface (adapt to your existing MonomialOrder API)

This section is intentionally abstract: it only declares the operations/props you will need.
Replace these by your actual definitions (you already have `MonomialOrder`, `leadingMonomial`,
`reduceFamily`, `IsGroebnerBasis₂`, etc.).
-/

section Groebner

-- If you already have `MonomialOrder` in your project, delete this stub and use yours.
-- The template only needs a handle `ord` plus a notion of leading monomial and initial ideal.
universe u
variable {σ : Type u}

/-- Minimal placeholder for a monomial order handle. Replace with your `MonomialOrder σ`. -/
structure MonOrder (σ : Type u) : Type (u+1) where
  dummy : Unit := ()

-- Back to our σ = Var m n
variable (ord : MonOrder (Fin m × Fin n))

/-- Leading monomial as a polynomial (placeholder). Replace by `ord.leadingMonomial`. -/
constant leadingMonomial : R m n k → R m n k

/-- Initial ideal (placeholder). Replace by your `initIdeal` definition. -/
constant initIdeal : Ideal (R m n k) → Ideal (R m n k)

/-- Gröbner basis predicate (placeholder). Replace by your `IsGroebnerBasis₂` etc. -/
constant IsGroebnerBasis : Set (R m n k) → Ideal (R m n k) → Prop

/-
Technical lemmas you will almost surely want (declare first, prove later).
-/

/-- (Hard) Leading monomial of a minor equals the anti-diagonal monomial under the chosen order. -/
theorem leadingMonomial_minor_eq_antiDiag
    {t : ℕ} (I : MinorIndex m n t) :
    leadingMonomial (m := m) (n := n) (k := k) ord (minor (m := m) (n := n) (k := k) I)
      = antiDiagMonom (m := m) (n := n) (k := k) I := by
  sorry

/--
(Hard) The initial ideal of the determinantal ideal is generated by anti-diagonal monomials of minors.
This is a typical "init(detIdeal) = span(antiDiagMonom)" statement.
-/
theorem init_detIdeal_eq_span_antiDiag
    (t : ℕ) :
    initIdeal (m := m) (n := n) (k := k) ord (detIdeal (m := m) (n := n) (k := k) t)
      =
    Ideal.span
      { f : R m n k | ∃ I : MinorIndex m n t, f = antiDiagMonom (m := m) (n := n) (k := k) I } := by
  sorry

/-- (Main milestone) All t×t minors form a Gröbner basis of `detIdeal t` for the chosen order. -/
theorem minors_isGroebnerBasis
    (t : ℕ) :
    IsGroebnerBasis (m := m) (n := n) (k := k) ord
      (minorSet (m := m) (n := n) (k := k) t)
      (detIdeal (m := m) (n := n) (k := k) t) := by
  sorry

/-
Optional: If you want the Sturmfels-style "width" characterization, declare it here.
You can implement `width` later via longest decreasing subsequence on a sequence extracted
from a monomial, or via a tableau insertion API.
-/

/-- Placeholder for a width invariant on monomials (hard/algorithmic). -/
constant width : R m n k → ℕ

/-- (Hard) Sturmfels-style characterization: monomial ∈ init(detIdeal (r+1)) ↔ width ≥ r+1. -/
theorem mem_init_rankIdeal_iff_width
    (r : ℕ) (M : R m n k) :
    M ∈ initIdeal (m := m) (n := n) (k := k) ord (rankIdeal (m := m) (n := n) (k := k) r)
      ↔ width (m := m) (n := n) (k := k) ord M ≥ r+1 := by
  sorry

end Groebner

/-! ### 5. Small “obvious” helper lemmas you can extend -/

section Helpers

/-- A minor is in the rank ideal iff its size matches (r+1). -/
lemma minor_mem_rankIdeal {r t : ℕ} (h : t = r+1) (I : MinorIndex m n t) :
    minor (m := m) (n := n) (k := k) I ∈ rankIdeal (m := m) (n := n) (k := k) r := by
  subst h
  simpa [rankIdeal] using minor_mem_detIdeal (m := m) (n := n) (k := k) I

/--
You will often need "closure under multiplication" facts:
if `f ∈ detIdeal t` then `g*f ∈ detIdeal t`.
-/
lemma mul_mem_detIdeal_left {t : ℕ} (g : R m n k) {f : R m n k}
    (hf : f ∈ detIdeal (m := m) (n := n) (k := k) t) :
    g * f ∈ detIdeal (m := m) (n := n) (k := k) t := by
  exact (detIdeal (m := m) (n := n) (k := k) t).mul_mem_left g hf

lemma mul_mem_detIdeal_right {t : ℕ} (g : R m n k) {f : R m n k}
    (hf : f ∈ detIdeal (m := m) (n := n) (k := k) t) :
    f * g ∈ detIdeal (m := m) (n := n) (k := k) t := by
  simpa [mul_comm] using mul_mem_detIdeal_left (m := m) (n := n) (k := k) (t := t) g hf

end Helpers

end Determinantal
