import Mathlib

open scoped BigOperators

namespace Determinantal

abbrev R (m n : ℕ) (k : Type*) [CommSemiring k] := MvPolynomial (Fin m × Fin n) k

noncomputable def genericMatrix (m n : ℕ) (k : Type*) [CommSemiring k] :
    Matrix (Fin m) (Fin n) (R m n k) :=
  fun i j => MvPolynomial.X (i, j)


@[simp] lemma genericMatrix_apply {m n : ℕ} (i : Fin m) (j : Fin n) (k : Type*) [CommSemiring k] :
    genericMatrix (m := m) (n := n) k i j = (MvPolynomial.X (i, j) : R m n k) := rfl

variable {k : Type*} [CommRing k]

structure MinorIndex (m n t : ℕ) where
  row : Fin t ↪ Fin m
  col : Fin t ↪ Fin n

attribute [simp] MinorIndex.row MinorIndex.col

noncomputable def minor {m n : ℕ} {t : ℕ} (I : MinorIndex m n t) : R m n k :=
  Matrix.det <|
    Matrix.submatrix (genericMatrix (m := m) (n := n) k) I.row I.col

def minorSet {m n : ℕ} (t : ℕ) : Set (R m n k) :=
  { f | ∃ I : MinorIndex m n t, f = minor (m := m) (n := n) (k := k) I }

@[simp] lemma mem_minorSet_iff {m n : ℕ} {t : ℕ} {f : R m n k} :
    f ∈ minorSet t
      ↔ ∃ I : MinorIndex m n t, f = minor (m := m) (n := n) (k := k) I := Iff.rfl

lemma minor_mem_minorSet {m n : ℕ} {t : ℕ} (I : MinorIndex m n t) :
    minor (k := k) I ∈ minorSet t :=
  ⟨I, rfl⟩


section FiniteInstances

variable {m n t : ℕ}

instance : Finite (MinorIndex m n t) := by
  classical
  refine Finite.of_injective (fun I : MinorIndex m n t => (I.row, I.col)) ?_
  intro I J h
  cases I with
  | mk rI cI =>
    cases J with
    | mk rJ cJ =>
      cases h
      rfl

noncomputable instance : Fintype (MinorIndex m n t) :=
  Fintype.ofFinite (MinorIndex m n t)


end FiniteInstances

section FiniteTools

variable {m n t : ℕ}

/-- `minorSet` is essentially the range of the `minor` function (up to symmetry of `=`). -/
lemma minorSet_eq_range {m n : ℕ} (t : ℕ) :
    minorSet (m := m) (n := n) (k := k) t
      = Set.range (minor (m := m) (n := n) (k := k) (t := t)) := by
  ext f
  constructor
  · rintro ⟨I, rfl⟩
    exact ⟨I, rfl⟩
  · rintro ⟨I, rfl⟩
    exact ⟨I, rfl⟩

/-- Finiteness of the set of all `t×t` minors. -/
lemma minorSet_finite {m n : ℕ} (t : ℕ) :
    (minorSet (m := m) (n := n) (k := k) t).Finite := by
  classical
  -- `Set.finite_range` uses `[Finite _]` on the domain
  simpa [minorSet_eq_range (k := k) (m := m) (n := n) (t := t)]
    using (Set.finite_range (minor (m := m) (n := n) (k := k) (t := t)))

end FiniteTools


/-- The usual `t×t` minor of an actual matrix `A`. -/
noncomputable def matrixMinor {S : Type*} [CommRing S]
    {m n t : ℕ} (A : Matrix (Fin m) (Fin n) S) (I : MinorIndex m n t) : S :=
  Matrix.det (Matrix.submatrix A I.row I.col)

section Eval

variable {m n t : ℕ}

variable {S : Type*} [CommRing S] [Algebra k S]

/-- Evaluate the generic polynomial ring `R m n k`
at a concrete matrix `A : Matrix (Fin m) (Fin n) S`. -/
noncomputable def evalMatrix (A : Matrix (Fin m) (Fin n) S) :
    R m n k →+* S :=
  MvPolynomial.eval₂Hom (algebraMap k S) (fun ij => A ij.1 ij.2)

@[simp] lemma evalMatrix_X (A : Matrix (Fin m) (Fin n) S) (i : Fin m) (j : Fin n) :
    evalMatrix (k := k) A (MvPolynomial.X (i, j))
      = A i j := by
  simp [evalMatrix]

@[simp] lemma evalMatrix_genericMatrix_apply
   (A : Matrix (Fin m) (Fin n) S) (i : Fin m) (j : Fin n) :
    evalMatrix (k := k)  A (genericMatrix m n k i j)
      = A i j := by
  simp [genericMatrix, evalMatrix]

/-- Key bridge lemma: evaluating a generic minor gives the corresponding minor of `A`. -/
lemma evalMatrix_minor (A : Matrix (Fin m) (Fin n) S) (I : MinorIndex m n t) :
    evalMatrix A (minor (k := k) I)
      = matrixMinor (A := A) I := by
  classical
  -- abbreviate the `t×t` submatrix of the generic matrix
  let M :
      Matrix (Fin t) (Fin t) (R m n k) :=
    Matrix.submatrix (genericMatrix m n k) I.row I.col
  have hdet := (RingHom.map_det (evalMatrix (k := k) A) M).symm
  -- then identify the mapped matrix with `A.submatrix`
  have hM :
      M.map (evalMatrix (k := k) (m := m) (n := n) A)
        = Matrix.submatrix A I.row I.col := by
    ext i j
    simp [M, evalMatrix, genericMatrix]
  -- finish
  simp [minor, matrixMinor, M] at *
  -- `hdet` is in the reverse direction we want
  simpa [M, hM] using hdet.symm

end Eval

/-! ### 2. Determinantal ideals -/

/-- The determinantal ideal generated by all t×t minors. -/
def detIdeal {m n : ℕ} (t : ℕ) : Ideal (R m n k) :=
  Ideal.span (minorSet (m := m) (n := n) (k := k) t)

lemma minor_mem_detIdeal {m n : ℕ} {t : ℕ} (I : MinorIndex m n t) :
    minor (m := m) (n := n) (k := k) I ∈ detIdeal (m := m) (n := n) (k := k) t := by
  exact Ideal.subset_span (minor_mem_minorSet (m := m) (n := n) (k := k) I)

lemma detIdeal_mono {m n : ℕ} {t₁ t₂ : ℕ}
  (h : minorSet (m := m) (n := n) (k := k) t₁ ⊆ minorSet t₂) :
    detIdeal (m := m) (n := n) (k := k) t₁ ≤ detIdeal t₂ := by
  exact Ideal.span_mono h

lemma detIdeal_le_iff {m n t} {J : Ideal (R m n k)} :
    detIdeal (m := m) (n := n) (k := k) t ≤ J
      ↔ minorSet (m := m) (n := n) (k := k) t ⊆ J := by
  classical
  constructor
  · intro h f hf
    exact h (Ideal.subset_span hf)
  · intro hs
    exact (Ideal.span_le).2 hs

lemma detIdeal_eq_span_range {m n : ℕ} (t : ℕ) :
    detIdeal (k := k) t
      = Ideal.span (Set.range (minor (m := m) (n := n) (k := k) (t := t))) := by
  simp [detIdeal, minorSet_eq_range (k := k) (m := m) (n := n) t]

noncomputable def minorFinset (m n t : ℕ) : Finset (R m n k) :=by
  classical
  exact Finset.univ.image (fun I : MinorIndex m n t => minor (m := m) (n := n) (k := k) (t := t) I)

lemma coe_minorFinset_eq_range (m n t : ℕ) :
    ((minorFinset (k := k) m n t : Finset (R m n k)) : Set (R m n k))
      = Set.range (minor (m := m) (n := n) (k := k) (t := t)) := by
  classical
  ext f
  constructor
  · intro hf
    rcases Finset.mem_image.1 hf with ⟨I, hI, rfl⟩
    exact ⟨I, rfl⟩
  · rintro ⟨I, rfl⟩
    exact Finset.mem_image.2 ⟨I, by simp, rfl⟩

lemma detIdeal_eq_span_minorFinset (m n t : ℕ) :
    detIdeal (m := m) (n := n) (k := k) t
      = Ideal.span (minorFinset (k := k) m n t : Set (R m n k)) := by
  classical
  simp only [detIdeal_eq_span_range (k := k) (m := m) (n := n) t,
    coe_minorFinset_eq_range (k := k) m n t]

lemma detIdeal_FG (m n t : ℕ) :
    (detIdeal (m := m) (n := n) (k := k) t).FG := by
  classical
  refine ⟨minorFinset (k := k) m n t, ?_⟩
  simp only [detIdeal_eq_span_minorFinset (k := k) (m := m) (n := n) t]

lemma minorSet_eq_empty_of_isEmpty {m n t : ℕ} (h : IsEmpty (MinorIndex m n t)) :
    minorSet (m := m) (n := n) (k := k) t = ∅ := by
  ext f
  constructor
  · rintro ⟨I, _⟩
    exact (h.false I).elim
  · intro hf
    exact False.elim (by simp only [Set.mem_empty_iff_false] at hf)

lemma detIdeal_eq_bot_of_isEmpty {m n t : ℕ} (h : IsEmpty (MinorIndex m n t)) :
    detIdeal (m := m) (n := n) (k := k) t = ⊥ := by
  classical
  simp only [detIdeal, minorSet_eq_empty_of_isEmpty (k := k) (m := m) (n := n) h, Ideal.span_empty]



/-! ## B. minors 的“系数环自然性”（base change） -/

section BaseChange

variable {S : Type*} [CommRing S]
variable {m n t : ℕ}

lemma genericMatrix_map (f : k →+* S) :
    (genericMatrix (m := m) (n := n) k).map (MvPolynomial.map f)
      = genericMatrix (m := m) (n := n) S := by
  ext i j
  simp [genericMatrix]

lemma map_minor (f : k →+* S) (I : MinorIndex m n t) :
    (MvPolynomial.map f)
        (minor (m := m) (n := n) (k := k) (t := t) I)
      = minor (m := m) (n := n) (k := S) (t := t) I := by
  classical
  unfold minor
  have hdet :
      (MvPolynomial.map f)
          (Matrix.det (Matrix.submatrix (genericMatrix (m := m) (n := n) k) I.row I.col))
        =
      Matrix.det
        ((Matrix.submatrix (genericMatrix (m := m) (n := n) k) I.row I.col).map
        (MvPolynomial.map f)) := by
    simpa using (RingHom.map_det (f := (MvPolynomial.map f))
      (M := Matrix.submatrix (genericMatrix (m := m) (n := n) k) I.row I.col))
  simpa [Matrix.submatrix_map, ←genericMatrix_map (k := k) (S := S) (m := m) (n := n) f] using hdet


lemma detIdeal_map (f : k →+* S) :
    Ideal.map (MvPolynomial.map f) (detIdeal (m := m) (n := n) (k := k) t)
      = detIdeal (m := m) (n := n) (k := S) t := by
  classical
  let φ : R m n k →+* R m n S := MvPolynomial.map f
  apply le_antisymm
  · refine (Ideal.map_le_iff_le_comap).2 ?_
    change Ideal.span (minorSet (m := m) (n := n) (k := k) t)
      ≤ Ideal.comap φ (Ideal.span (minorSet (m := m) (n := n) (k := S) t))
    refine (Ideal.span_le).2 ?_
    intro x hx
    rcases hx with ⟨I, rfl⟩
    have : φ (minor (m := m) (n := n) (k := k) (t := t) I)
        ∈ Ideal.span (minorSet (m := m) (n := n) (k := S) t) :=
      Ideal.subset_span ⟨I, map_minor f I⟩
    simpa [φ, map_minor (k := k) (S := S) (m := m) (n := n) (t := t) f I] using this
  · change Ideal.span (minorSet (m := m) (n := n) (k := S) t)
      ≤ Ideal.map (MvPolynomial.map f) (Ideal.span (minorSet (m := m) (n := n) (k := k) t))
    refine (Ideal.span_le).2 ?_
    intro x hx
    rcases hx with ⟨I, rfl⟩
    have hx0 :
        minor (m := m) (n := n) (k := k) (t := t) I
          ∈ detIdeal (m := m) (n := n) (k := k) t :=
      minor_mem_detIdeal (m := m) (n := n) (k := k) (t := t) I
    have : (MvPolynomial.map f)
        (minor (m := m) (n := n) (k := k) (t := t) I)
        ∈ Ideal.map (MvPolynomial.map f) (detIdeal (m := m) (n := n) (k := k) t) :=
      Ideal.mem_map_of_mem (MvPolynomial.map f) hx0
    simpa [map_minor (k := k) (S := S) (m := m) (n := n) (t := t) f I] using this

end BaseChange

/-! ## C. 具体矩阵 minors 的自然性 -/

section ConcreteMatrix

variable {S T : Type*} [CommRing S] [CommRing T]
variable {m n t : ℕ}


/-- `matrixMinor` 在环同态下自然：`f (minor(A)) = minor(A.map f)`。 -/
lemma matrixMinor_map (f : S →+* T) (A : Matrix (Fin m) (Fin n) S) (I : MinorIndex m n t) :
    f (matrixMinor (m := m) (n := n) (t := t) A I)
      = matrixMinor (m := m) (n := n) (t := t) (A.map f) I := by
  classical
  unfold matrixMinor
  simpa [Matrix.submatrix_map] using
    (RingHom.map_det f (Matrix.submatrix A I.row I.col))

end ConcreteMatrix


namespace MinorIndex

variable {m n t : ℕ}

/-- Permute the *row-indexing* of a `MinorIndex` by `σ`. -/
def rowPerm (I : MinorIndex m n t) (σ : Equiv.Perm (Fin t)) : MinorIndex m n t :=
  { row := σ.toEmbedding.trans I.row, col := I.col }

/-- Permute the *column-indexing* of a `MinorIndex` by `σ`. -/
def colPerm (I : MinorIndex m n t) (σ : Equiv.Perm (Fin t)) : MinorIndex m n t :=
  { row := I.row, col := σ.toEmbedding.trans I.col }

@[simp] lemma rowPerm_row (I : MinorIndex m n t) (σ : Equiv.Perm (Fin t)) :
    (I.rowPerm σ).row = σ.toEmbedding.trans I.row := rfl

@[simp] lemma rowPerm_col (I : MinorIndex m n t) (σ : Equiv.Perm (Fin t)) :
    (I.rowPerm σ).col = I.col := rfl

@[simp] lemma colPerm_row (I : MinorIndex m n t) (σ : Equiv.Perm (Fin t)) :
    (I.colPerm σ).row = I.row := rfl

@[simp] lemma colPerm_col (I : MinorIndex m n t) (σ : Equiv.Perm (Fin t)) :
    (I.colPerm σ).col = σ.toEmbedding.trans I.col := rfl

end MinorIndex

section SignLemmas

variable {m n t : ℕ}

noncomputable def eps (σ : Equiv.Perm (Fin t)) : R m n k :=
  (((Equiv.Perm.sign σ : ℤˣ) : ℤ) : R m n k)

local notation "ε" => (eps (m := m) (n := n) (k := k) (t := t))

/-- Row permutation changes a minor by `sign σ`. -/
lemma minor_rowPerm (I : MinorIndex m n t) (σ : Equiv.Perm (Fin t)) :
    minor (m := m) (n := n) (k := k) (t := t) (I.rowPerm σ)
      = ε σ * minor (m := m) (n := n) (k := k) (t := t) I := by
  classical
  -- B is the t×t submatrix whose det defines the minor
  set B : Matrix (Fin t) (Fin t) (R m n k) :=
    Matrix.submatrix (genericMatrix (m := m) (n := n) k) I.row I.col
  -- unfold and apply `Matrix.det_permute`
  simp only [minor, MinorIndex.rowPerm] at *
  calc
    (Matrix.submatrix (genericMatrix (m := m) (n := n) k) (σ.toEmbedding.trans I.row) I.col).det
        = (B.submatrix (⇑σ) id).det := rfl
    _ = ε σ * B.det := by simpa using (Matrix.det_permute (σ := σ) (M := B))
    _ = ε σ * (Matrix.submatrix (genericMatrix (m := m) (n := n) k) I.row I.col).det := by
          simp [B]
    _ = ε σ * minor (m := m) (n := n) (k := k) (t := t) I := by
          simp only [minor]

/-- Column permutation changes a minor by `sign σ`. -/
lemma minor_colPerm (I : MinorIndex m n t) (σ : Equiv.Perm (Fin t)) :
    minor (m := m) (n := n) (k := k) (t := t) (I.colPerm σ)
      = ε σ * minor (m := m) (n := n) (k := k) (t := t) I := by
  classical
  set B : Matrix (Fin t) (Fin t) (R m n k) :=
    Matrix.submatrix (genericMatrix (m := m) (n := n) k) I.row I.col
  simp only [minor, MinorIndex.colPerm] at *
  calc
    (Matrix.submatrix (genericMatrix (m := m) (n := n) k) I.row (σ.toEmbedding.trans I.col)).det
        = (B.submatrix id (⇑σ)).det := rfl
    _ = ε σ * B.det := by simpa using (Matrix.det_permute' (σ := σ) (M := B))
    _ = ε σ * minor (m := m) (n := n) (k := k) (t := t) I := by
          simp [minor, B]

/-- Permuting both row- and column-indexings multiplies by the product of the two signs. -/
lemma minor_rowPerm_colPerm (I : MinorIndex m n t)
    (σ τ : Equiv.Perm (Fin t)) :
    minor (m := m) (n := n) (k := k) (t := t) ((I.rowPerm σ).colPerm τ)
      = (ε τ) * (ε σ) * minor (m := m) (n := n) (k := k) (t := t) I := by
  -- do columns-after-rows
  simpa [mul_assoc, mul_left_comm, mul_comm] using
    (minor_colPerm (m := m) (n := n) (k := k) (t := t) (I := I.rowPerm σ) τ).trans <|
      by
        simp only [minor_rowPerm (m := m) (n := n) (k := k) (t := t) (I := I) (σ := σ),
          mul_left_comm]

end SignLemmas






end Determinantal
